### ISSUE TITLE
how to update python

### ISSUE THREAD

**Issue by jayshin-agc** [agcteam/git_primer#5]
can you guide me through how we can upgrade python or use anaconda?

**Comment by biofilos** [comment]
Absolutely.
Using anaconda is going to be the easiest way
This is how I set up anaconda and other bioiformatics tools (taken from https://bioconda.github.io/user/install.html#install-conda

1. If on Mac:
```
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
sh Miniconda3-latest-MacOSX-x86_64.sh
```
1. If on Linux:
```
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
sh Miniconda3-latest-Linux-x86_64.sh
```
When you follow the instructions from the step above, you will see an option to initialize your terminal with anaconda. I recommend to say yes. In that way, you will have access to anaconda all the time.

2. Set up channels to download and install packages
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

After that, you can start using the latest Python3 version available in Anaconda.
To search for packages:
`conda search bedtools`
To Install packages
`conda install bedtools`

I will be monitoring this issue, in case you have any trouble of have any other questions

**Comment by jayshin-agc** [comment]
cool! it worked. thanks!
